### ISSUE TITLE
Missing Platform.sh version.txt file in phar causes warning

### ISSUE THREAD

**Issue by kasperg** [xendk/dais#5]
After updating to 0.6.0 I get the following warning when running dais as a Phar file. 

`
Warning: file_get_contents(phar:///[...]/dais-0.6.0.phar/vendor/platformsh/client/src/Connection/../../version.txt): failed to open stream: phar error: "vendor/platformsh/client/version.txt" is not a file in phar "[...]/dais-0.6.0.phar" in phar:///[...]/dais-0.6.0.phar/vendor/platformsh/client/src/Connection/Connector.php on line 93
`

It does not seem to affect usage though.

**Comment by xendk** [comment]
Hmm, maybe I need to tell box that txt files should be included?

**Comment by xendk** [comment]
Fixed
